name: Deploy Allure Report

on:
  push:
    branches:
      - samad-updated

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4